### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by amervelic** [lisawray/groupie#208] opened 2018-09-09 11:01 UTC
too slow for more than 100 items

**Comment by ExpensiveBelly** [comment] 2018-09-22 14:34
We improved the speed by passing our DiffUtil. I created a PR for it: https://github.com/lisawray/groupie/pull/209

**Comment by lisawray** [comment] 2018-11-07 07:09
Closing as a duplicate of https://github.com/lisawray/groupie/issues/161

**Closed by lisawray** 2018-11-07 07:09 UTC
