### ISSUE TITLE
RecyclerView Gets Struck

### ISSUE THREAD

**Issue by ananth10** [lisawray/groupie#84] opened 2017-05-10 05:28 UTC
I am displaying lot of product items in recyclerview . Every product will have banner and items. so i have decided to use Recyclerview as Vertical(for banner) and Recyclerview as horizontal(product items)

**Issue :
![screenshot_20170426-160235 1](https://cloud.githubusercontent.com/assets/13381242/25884382/93fe6a52-356f-11e7-9ef4-900cf32df7a5.jpg)
**

  When i scroll down the vertical recyclerview . it gets struck a bit but if scroll up there is no struck

and if all the banners and items loaded once. then no struck at all. why recyclerview gets strcuk at 

first time? . for you reference below i have attached the screenshot

**Comment by lisawray** [comment] 2017-05-15 21:18
Sorry, I really can't tell what the problem is in the screenshot.  It's not clear what's "stuck" to me.

If you can post a minimal example project or example code that reproduces the problem, I may be able to help.

**Comment by ananth10** [comment] 2017-05-17 07:29
@lisawray  Thanks for quick response.. the problem is vetical(Y axis) recyclerview not scrolling smoothly when i added horizontal(X axis) recyclerview in adapter of Y recyclerview. 

**Y - Axis RecyclerView Adapter**

```
package com.lovetohave.adapters;

import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.ActivityOptionsCompat;
import android.support.v4.util.Pair;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.text.TextUtils;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.google.firebase.analytics.FirebaseAnalytics;
import com.lovetohave.R;
import com.lovetohave.love.ExploreByThemeDetails;
import com.lovetohave.recyclerview.decoration.discover.DiscoverHeaderViewHolder;
import com.lovetohave.recyclerview.decoration.discover.DiscoverItemViewHolder;
import com.lovetohave.utils.PrefUtil;
import com.squareup.picasso.Picasso;

import java.util.ArrayList;
import java.util.HashMap;


/**
 * Created by Babu on 12/27/2016.
 */

public class DiscoverFeedsAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {

    private FirebaseAnalytics mFirebaseAnalytics;
    private ArrayList<ArrayList<HashMap<String, String>>> mDiscoverFeedsList;
    private ArrayList<HashMap<String, String>> mExploreThemeList;
    private ArrayList<HashMap<String, String>> mProductTypeList;
    private ArrayList<HashMap<String, String>> mInnerProductList;
    private final int ITEM = 1, HEADER = 0;
    private Context mContext;
    HashMap<String,RecyclerView.Adapter> mAdapters=new HashMap<>();

    public DiscoverFeedsAdapter(Context context, ArrayList<ArrayList<HashMap<String, String>>> mFeed, ArrayList<HashMap<String, String>> mProductList, ArrayList<HashMap<String, String>> mExploreList, Boolean nodatafound, RecyclerView recyclerView, HashMap<String,RecyclerView.Adapter> adapters) {
        this.mDiscoverFeedsList = mFeed;
        this.mExploreThemeList = mExploreList;
        this.mProductTypeList = mProductList;
        this.mContext = context;
        mFirebaseAnalytics = FirebaseAnalytics.getInstance(mContext);
//        this.mAdapters=adapters;

    }

    @Override
    public int getItemCount() {
        return mProductTypeList.size() + 1;
    }

    @Override
    public int getItemViewType(int position) {
        if (position == 0) {
            return HEADER;
        }

        return ITEM;
    }


    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup viewGroup, int viewType) {
        RecyclerView.ViewHolder viewHolder = null;
        LayoutInflater inflater = LayoutInflater.from(viewGroup.getContext());
        switch (viewType) {
            case HEADER:
                View v1 = inflater.inflate(R.layout.discover_header, viewGroup, false);
                viewHolder = new DiscoverHeaderViewHolder(v1);
                break;
            case ITEM:
                View v2 = inflater.inflate(R.layout.explore_product, viewGroup, false);
                viewHolder = new DiscoverItemViewHolder(v2);
                break;
        }
        return viewHolder;
    }

    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
        switch (viewHolder.getItemViewType()) {
            case HEADER:
                DiscoverHeaderViewHolder headerViewHolder = (DiscoverHeaderViewHolder) viewHolder;
                configureHeaderViewHolder(headerViewHolder, position);
                break;
            case ITEM:
                DiscoverItemViewHolder itemViewHolder = (DiscoverItemViewHolder) viewHolder;
                int pos = position - 1;
                configureItemViewHolder(itemViewHolder, pos);
                break;
        }
    }

    private void configureHeaderViewHolder(DiscoverHeaderViewHolder headerHolder, final int position) {
        try {

            LinearLayoutManager layoutManager
                    = new LinearLayoutManager(mContext, LinearLayoutManager.HORIZONTAL, false);
            headerHolder.getThemeRecyclerView().setLayoutManager(layoutManager);
            headerHolder.getThemeRecyclerView().setHasFixedSize(false);
            headerHolder.getThemeRecyclerView().setNestedScrollingEnabled(false);
            headerHolder.getThemeRecyclerView().setItemViewCacheSize(50);
            headerHolder.getThemeRecyclerView().setDrawingCacheEnabled(true);
//            headerHolder.getThemeRecyclerView().setDrawingCacheQuality(View.DRAWING_CACHE_QUALITY_HIGH);

            if (mExploreThemeList.size() > 0) {
                headerHolder.getTitle().setVisibility(View.VISIBLE);
                headerHolder.getThemeRecyclerView().setVisibility(View.VISIBLE);
                ExploreByThemeAdapter mAdapter = new ExploreByThemeAdapter(mContext, mExploreThemeList);
                headerHolder.getThemeRecyclerView().setAdapter(mAdapter);
            } else {
                headerHolder.getTitle().setVisibility(View.GONE);
                headerHolder.getThemeRecyclerView().setVisibility(View.GONE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void configureItemViewHolder(final DiscoverItemViewHolder itemViewHolder, final int position) {
        try {
            LinearLayoutManager layoutManager
                    = new LinearLayoutManager(mContext, LinearLayoutManager.HORIZONTAL, false);
            itemViewHolder.getProductList().setLayoutManager(layoutManager);
            itemViewHolder.getProductList().setHasFixedSize(false);
            itemViewHolder.getProductList().setNestedScrollingEnabled(false);
            itemViewHolder.getProductList().setItemViewCacheSize(200);
            itemViewHolder.getProductList().setDrawingCacheEnabled(true);
            if (mDiscoverFeedsList.size() > 0) {
                mInnerProductList = mDiscoverFeedsList.get(position);
                if (mInnerProductList.size() > 0) {
                    itemViewHolder.getArrowImage().setVisibility(View.VISIBLE);
                    itemViewHolder.getProductList().setVisibility(View.VISIBLE);
                    ExploreProductAdapter mAdapter= new ExploreProductAdapter(mContext, mInnerProductList,mProductTypeList.get(position).get("name"),mProductTypeList.get(position).get("img_banner"),mProductTypeList.get(position).get("description"),mProductTypeList.get(position).get("shortDes"),mProductTypeList.get(position).get("showTitle"),mProductTypeList.get(position).get("id"),mProductTypeList.get(position).get("address"),mProductTypeList.get(position).get("phoneNo"),mProductTypeList.get(position).get("latlng"));
                        itemViewHolder.getProductList().setAdapter(mAdapters.get("adapter"+position));
                    itemViewHolder.getProductList().setAdapter(mAdapter);

                } else {
                    itemViewHolder.getProductList().setVisibility(View.GONE);
                    itemViewHolder.getArrowImage().setVisibility(View.GONE);
                }
            }
        } catch (Exception e) {

            e.printStackTrace();
        }
        try {
            if (position == 0) {
                itemViewHolder.getTrending().setVisibility(View.VISIBLE);
            } else {
                itemViewHolder.getTrending().setVisibility(View.GONE);
            }
            if (mProductTypeList.get(position).get("showTitle").equals("true")) {
                itemViewHolder.getBannerTitle().setVisibility(View.VISIBLE);
                itemViewHolder.getTransImage().setVisibility(View.VISIBLE);
                itemViewHolder.getBannerTitle().setText(mProductTypeList.get(position).get("name"));
            } else {
                itemViewHolder.getTransImage().setVisibility(View.GONE);
                itemViewHolder.getBannerTitle().setVisibility(View.GONE);
            }
            if (mProductTypeList.get(position).get("collectionType").equals("2") || mProductTypeList.get(position).get("collectionType").equals("5")) {
                itemViewHolder.getTypeFlag().setBackgroundResource(R.drawable.mark_as_fulfilled);
                itemViewHolder.getTypeFlag().setTextColor(mContext.getResources().getColor(R.color.white));
                itemViewHolder.getTypeFlag().setText(mContext.getString(R.string.cash_fund));
                itemViewHolder.getTypeFlag().setVisibility(View.VISIBLE);
            } else if (mProductTypeList.get(position).get("collectionType").equals("6")) {
                itemViewHolder.getTypeFlag().setBackgroundResource(R.drawable.mark_as_local_store);
                itemViewHolder.getTypeFlag().setTextColor(mContext.getResources().getColor(R.color.white));
                itemViewHolder.getTypeFlag().setText(mContext.getString(R.string.experience));
                itemViewHolder.getTypeFlag().setVisibility(View.VISIBLE);
            } else if (mProductTypeList.get(position).get("collectionType").equals("7")) {
                itemViewHolder.getTypeFlag().setBackgroundResource(R.drawable.mark_as_experiance);
                itemViewHolder.getTypeFlag().setTextColor(mContext.getResources().getColor(R.color.username_txt));
                itemViewHolder.getTypeFlag().setText(mContext.getString(R.string.local_store));
                itemViewHolder.getTypeFlag().setVisibility(View.VISIBLE);
            } else {
                itemViewHolder.getTypeFlag().setVisibility(View.GONE);
            }

            if (!TextUtils.isEmpty(mProductTypeList.get(position).get("img_banner"))) {
                Picasso.with(mContext)
                        .load(mProductTypeList.get(position).get("img_banner")) // image url goes here
                        .fit()
                        .into(itemViewHolder.getBannerImage());
            } else {
                Picasso.with(mContext)
                        .load(R.drawable.banner_no_image) // image url goes here
                        .placeholder(itemViewHolder.getBannerImage().getDrawable())
                        .fit()
                        .into(itemViewHolder.getBannerImage());

            }

            itemViewHolder.getBannerImage().setOnClickListener(new View.OnClickListener() {
                @SuppressLint("NewApi")
                @Override
                public void onClick(View view) {
                    String mDesc = "";
                    if (!TextUtils.isEmpty(PrefUtil.getData("user_name", mContext))) {
                        mDesc = PrefUtil.getData("user_name", mContext) + " clicked " + mProductTypeList.get(position).get("name") + " trend";
                    } else {
                        mDesc = "User " + " clicked " + mProductTypeList.get(position).get("name") + " trend";
                    }
                    Bundle params = new Bundle();
                    params.putString("event_name", "trend_" + mProductTypeList.get(position).get("name") + "_clicked");
                    params.putString("event_description", mDesc);
                    mFirebaseAnalytics.logEvent(mContext.getString(R.string.event_type), params);
                    Intent intent = new Intent(mContext, ExploreByThemeDetails.class);
                    intent.putExtra("name", mProductTypeList.get(position).get("name"));
                    intent.putExtra("image", mProductTypeList.get(position).get("img_banner"));
                    intent.putExtra("desc", mProductTypeList.get(position).get("description"));
                    intent.putExtra("shortDes", mProductTypeList.get(position).get("shortDes"));
                    intent.putExtra("showTitle", mProductTypeList.get(position).get("showTitle"));
                    intent.putExtra("id", mProductTypeList.get(position).get("id"));
                    intent.putExtra("address", mProductTypeList.get(position).get("address"));
                    intent.putExtra("phone", mProductTypeList.get(position).get("phoneNo"));
                    intent.putExtra("latlng", mProductTypeList.get(position).get("latlng"));
                    intent.putExtra("type", "trend");
                    Pair<View, String> p1 = Pair.create((View) itemViewHolder.getBannerImage(), mContext.getString(R.string.product_banner_image_transition_image));
                    Pair<View, String> p2 = Pair.create((View) itemViewHolder.getBannerTitle(), mContext.getString(R.string.product_banner_title_transition_name));
                    ActivityOptionsCompat options = ActivityOptionsCompat.
                            makeSceneTransitionAnimation((Activity) mContext, p1, p2);
                    mContext.startActivity(intent, options.toBundle());
                }
            });


        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}

```

**X - Axis RecyclerView Adapter**

```
package com.lovetohave.adapters;

import android.annotation.TargetApi;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.support.v4.app.ActivityOptionsCompat;
import android.support.v4.util.Pair;
import android.support.v7.widget.RecyclerView;
import android.text.TextUtils;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import com.google.firebase.analytics.FirebaseAnalytics;
import com.lovetohave.R;
import com.lovetohave.love.ExploreByThemeDetails;
import com.lovetohave.utils.PrefUtil;
import com.squareup.picasso.Picasso;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Created by Babu on 10/17/2016.
 */
public class ExploreByThemeAdapter extends
        RecyclerView.Adapter<ExploreByThemeAdapter.ViewHolder> {
    ArrayList<HashMap<String, String>> mExploreList;
    Context mContext;
    private FirebaseAnalytics mFirebaseAnalytics;
    // Provide a direct reference to each of the views within a data item
    // Used to cache the views within the item layout for fast access

    public ExploreByThemeAdapter(Context context, ArrayList<HashMap<String, String>> mList) {
        this.mContext = context;
        this.mExploreList = mList;
        mFirebaseAnalytics = FirebaseAnalytics.getInstance(mContext);
    }

    public class ViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
        private final ImageView mTransImage;
        // Your holder should contain a member variable
        // for any view that will be set as you render a row
        public TextView mItemType;
        public ImageView ItemImage;

        // We also create a constructor that accepts the entire item row
        // and does the view lookups to find each subview
        public ViewHolder(View itemView) {
            // Stores the itemView in a public final member variable that can be used
            // to access the context from any ViewHolder instance.
            super(itemView);

            mItemType = (TextView) itemView.findViewById(R.id.item_type);
            ItemImage = (ImageView) itemView.findViewById(R.id.item_image);
            mTransImage = (ImageView) itemView.findViewById(R.id.transimage);

        }

        @Override
        public void onClick(View v) {
        }
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        Context context = parent.getContext();
        LayoutInflater inflater = LayoutInflater.from(context);

        // Inflate the custom layout
        View contactView = inflater.inflate(R.layout.explore_theme_inner_item, parent, false);

        // Return a new holder instance
        ViewHolder viewHolder = new ViewHolder(contactView);

        return viewHolder;
    }

    @Override
    public void onBindViewHolder(final ViewHolder holder, final int position) {
        try {
        if (mExploreList.get(position).get("showTitle").equals("true")) {
            holder.mItemType.setVisibility(View.VISIBLE);
            holder.mTransImage.setVisibility(View.VISIBLE);
            holder.mItemType.setText(mExploreList.get(position).get("name"));
        } else {
            holder.mItemType.setVisibility(View.GONE);
            holder.mTransImage.setVisibility(View.GONE);
        }

        if (!TextUtils.isEmpty(mExploreList.get(position).get("img"))) {
            Picasso.with(mContext)
                    .load(mExploreList.get(position).get("img")) // image url goes here
                    .placeholder(R.drawable.gift_no_image_available)
                    .fit()
                    .into(holder.ItemImage);
        } else {
            Picasso.with(mContext)
                    .load(R.drawable.gift_no_image_available) // image url goes here
                    .placeholder(R.drawable.gift_no_image_available)
                    .fit()
                    .into(holder.ItemImage);
        }




            holder.ItemImage.setOnClickListener(new View.OnClickListener() {
                @TargetApi(Build.VERSION_CODES.JELLY_BEAN)
                @Override
                public void onClick(View view) {
                    String mDesc="";
                    if (!TextUtils.isEmpty(PrefUtil.getData("user_name", mContext))) {
                        mDesc = PrefUtil.getData("user_name", mContext) + " clicked " +mExploreList.get(position).get("name")+" theme";
                    } else {
                        mDesc = "User " + " clicked " +mExploreList.get(position).get("name")+" theme";
                    }
                    //created fabric event log
                    Bundle params = new Bundle();
                    params.putString("event_name", "Theme_"+mExploreList.get(position).get("name")+"_clicked");
                    params.putString("event_description", mDesc);
                    mFirebaseAnalytics.logEvent(mContext.getString(R.string.event_type), params);
                    Context context = view.getContext();
                    Intent intent = new Intent(mContext, ExploreByThemeDetails.class);
                    intent.putExtra("name", mExploreList.get(position).get("name"));
                    intent.putExtra("image", mExploreList.get(position).get("img_banner"));
                    intent.putExtra("desc", mExploreList.get(position).get("description"));
                    intent.putExtra("shortDes", mExploreList.get(position).get("shortDes"));
                    intent.putExtra("showTitle", mExploreList.get(position).get("showTitle"));
                    intent.putExtra("id", mExploreList.get(position).get("id"));
                    intent.putExtra("address", mExploreList.get(position).get("address"));
                    intent.putExtra("phone", mExploreList.get(position).get("phoneNo"));
                    intent.putExtra("latlng", mExploreList.get(position).get("latlng"));
                    intent.putExtra("type", "theme");
                    Pair<View, String> p1 = Pair.create((View) holder.ItemImage, mContext.getString(R.string.product_banner_image_transition_image));
                    Pair<View, String> p2 = Pair.create((View) holder.mItemType, mContext.getString(R.string.product_banner_title_transition_name));
                    ActivityOptionsCompat options = ActivityOptionsCompat.
                            makeSceneTransitionAnimation((Activity) mContext, p1, p2);
                    mContext.startActivity(intent, options.toBundle());
                }
            });

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    public int getItemCount() {
        return mExploreList.size();
    }

}
```

When Y-Axis recyclerview's all child view is visible then scrolling is smooth. please have look on 
**configureItemViewHolder** here i am setting adapter for X- aixs RecyclerView. . let me know am i coding right way or wrong?

**Comment by andhie** [comment] 2017-05-17 10:43
i'm just guessing based on the description. 
but try add `android:nestedScrollingEnabled="false"` or `recyclerView.setNestedScrollingEnabled(false);` in the horizontal RecyclerView

**Comment by ananth10** [comment] 2017-05-18 04:05
@andhie I have already done.

**Comment by amirulzin** [comment] 2017-08-15 10:18
It seems you are holding the UI thread even more when trying to initialize the horizontal RecyclerView during `OnBindViewHolder()` of the vertical RecyclerView. 

There's a ton it does the first time it scrolls down, which explains why it only becomes smooth when you scroll back up (since its already binded and initialized).

Here's the culprit code section in **Y - Axis RecyclerView Adapter**:

```java
    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int position) {
        switch (viewHolder.getItemViewType()) {
            case HEADER:
                DiscoverHeaderViewHolder headerViewHolder = (DiscoverHeaderViewHolder) viewHolder;
                configureHeaderViewHolder(headerViewHolder, position);
                break;
            case ITEM:
                DiscoverItemViewHolder itemViewHolder = (DiscoverItemViewHolder) viewHolder;
                int pos = position - 1;
                configureItemViewHolder(itemViewHolder, pos);
                break;
        }
    }

    private void configureHeaderViewHolder(DiscoverHeaderViewHolder headerHolder, final int position) {
        try {

            LinearLayoutManager layoutManager
                    = new LinearLayoutManager(mContext, LinearLayoutManager.HORIZONTAL, false);
            headerHolder.getThemeRecyclerView().setLayoutManager(layoutManager);
            headerHolder.getThemeRecyclerView().setHasFixedSize(false);
            headerHolder.getThemeRecyclerView().setNestedScrollingEnabled(false);
            headerHolder.getThemeRecyclerView().setItemViewCacheSize(50);
            headerHolder.getThemeRecyclerView().setDrawingCacheEnabled(true);
//            headerHolder.getThemeRecyclerView().setDrawingCacheQuality(View.DRAWING_CACHE_QUALITY_HIGH);

            if (mExploreThemeList.size() > 0) {
                headerHolder.getTitle().setVisibility(View.VISIBLE);
                headerHolder.getThemeRecyclerView().setVisibility(View.VISIBLE);
                ExploreByThemeAdapter mAdapter = new ExploreByThemeAdapter(mContext, mExploreThemeList);
                headerHolder.getThemeRecyclerView().setAdapter(mAdapter);
            } else {
                headerHolder.getTitle().setVisibility(View.GONE);
                headerHolder.getThemeRecyclerView().setVisibility(View.GONE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

Instead of initializing it there in `OnBindViewHolder()`, I suggest to initialize the horizontal RecyclerView somewhere earlier (or maybe later after the layout of the vertical RecyclerView have been created) and let it bind to the reference of that when it was first binded. 

If that's not feasible, you can try to wrap the execution in a `View.post( ... )` to delay the execution of the initialization towards later time in the main thread. You might need to call `notifyItemChanged()` as well.

**Comment by lisawray** [comment] 2017-11-13 08:07
Closing this because it doesn't seem related to groupie.  Thanks for trying to help @amirulzin!

**Closed by lisawray** 2017-11-13 08:07 UTC
Labels: help wanted
